// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 72);
    lv_obj_set_height(ui_Arc1, 72);
    lv_obj_set_x(ui_Arc1, 7);
    lv_obj_set_y(ui_Arc1, -63);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);


    ui_Colorwheel1 = lv_colorwheel_create(ui_Screen1, true);
    lv_obj_set_width(ui_Colorwheel1, 99);
    lv_obj_set_height(ui_Colorwheel1, 104);
    lv_obj_set_x(ui_Colorwheel1, 16);
    lv_obj_set_y(ui_Colorwheel1, 45);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);


}
